export const destinations = [
  {
    title: 'Lanzarote',
    smallTitle: 'Canary Islands - Spain - Europe',
    image1: '/assets/images/lanzarote_1.jpg',
    image2: '/assets/images/lanzarote_2.jpg',
    image3: '/assets/images/lanzarote_3.jpg',
    imageBig: '/assets/images/lanzarote_big.jpg',
    description:
      "Lanzarote is a Spanish island, the northernmost and easternmost of the autonomous Canary Islands in the Atlantic Ocean. It is located approximately 125 kilometres (78 miles) off the north coast of Africa and 1,000 kilometres (621 miles) from the Iberian Peninsula. Covering 845.94 square kilometres (326.62 square miles), Lanzarote is the fourth-largest of the islands in the archipelago. With 151,953 inhabitants at the start of 2019, it is the third most populous Canary Island, after Tenerife and Gran Canaria. Located in the centre-west of the island is Timanfaya National Park, one of its main attractions. The island was declared a biosphere reserve by UNESCO in 1993. The island's capital is Arrecife.",
  },
  {
    title: 'Paris',
    smallTitle: 'France - Europe',
    image1: '/assets/images/paris_1.jpg',
    image2: '/assets/images/paris_2.jpg',
    image3: '/assets/images/paris_3.jpg',
    imageBig: '/assets/images/paris_big.jpg',
    description:
      "Paris is the capital and most populous city of France, with an estimated population of 2,175,601 residents as of 2018, in an area of more than 105 square kilometres (41 square miles). Since the 17th century, Paris has been one of Europe's major centres of finance, diplomacy, commerce, fashion, science and arts. The City of Paris is the centre and seat of government of the Île-de-France, or Paris Region, which has an estimated official 2019 population of 12,213,364, or about 18 percent of the population of France. The Paris Region had a GDP of €709 billion ($808 billion) in 2017. According to the Economist Intelligence Unit Worldwide Cost of Living Survey in 2018, Paris was the second most expensive city in the world, after Singapore, and ahead of Zürich, Hong Kong, Oslo and Geneva.",
  },
  {
    title: 'Réunion',
    smallTitle: 'France - Europe',
    image1: '/assets/images/run_1.jpg',
    image2: '/assets/images/run_2.jpg',
    image3: '/assets/images/run_3.jpg',
    imageBig: '/assets/images/run_big.jpg',
    description:
      'Réunion is a French overseas department located in the Indian Ocean. It is situated east of Madagascar and about 175 kilometres (109 mi) southwest of Mauritius, the nearest island. As of January 2020, it had a population of 859,959. The island has been inhabited since the 16th century, when people from France and Madagascar settled there.',
  },
  {
    title: 'Switzerland',
    smallTitle: 'Swiss Confederation - Europe',
    image1: '/assets/images/switzerland_1.jpg',
    image2: '/assets/images/switzerland_2.jpg',
    image3: '/assets/images/switzerland_3.jpg',
    imageBig: '/assets/images/switzerland_big.jpg',
    description: `Switzerland, officially the Swiss Confederation, is a country situated at the confluence of Western, Central, and Southern Europe. It is a federal republic composed of 26 cantons, with federal authorities based in Bern. Switzerland is a landlocked country bordered by Italy to the south, France to the west, Germany to the north, and Austria and Liechtenstein to the east.`,
  },
  {
    title: 'Mallorca',
    smallTitle: 'Balearic Islands - Spain - Europe',
    image1: '/assets/images/mallorca_1.jpg',
    image2: '/assets/images/mallorca_2.jpg',
    image3: '/assets/images/mallorca_3.jpg',
    imageBig: '/assets/images/mallorca_big.jpg',
    description: `Mallorca or Majorca is the largest island in the Balearic Islands, which are part of Spain and located in the Mediterranean. The native language, as on the rest of the Balearic Islands, is Catalan, which is co-official with Spanish.`,
  },
  {
    title: 'Sevilla',
    smallTitle: 'Andalusia - Spain - Europe',
    image1: '/assets/images/sevilla_1.jpg',
    image2: '/assets/images/sevilla_2.jpg',
    image3: '/assets/images/sevilla_3.jpg',
    imageBig: '/assets/images/sevilla_big.jpg',
    description: `Seville is the capital and largest city of the Spanish autonomous community of Andalusia and the province of Seville. It is situated on the lower reaches of the River Guadalquivir, in the southwest of the Iberian Peninsula. Seville has a municipal population of about 690,000 as of 2016, and a metropolitan population of about 1.5 million, making it the largest city in Andalusia, the fourth-largest city in Spain and the 30th most populous municipality in the European Union.`,
  },
  {
    title: 'Puerto Rico',
    smallTitle: 'Caribbean, West Indies',
    image1: '/assets/images/pr_1.jpg',
    image2: '/assets/images/pr_2.jpg',
    image3: '/assets/images/pr_3.jpg',
    imageBig: '/assets/images/pr_big.jpg',
    description: `Puerto Rico, officially the Commonwealth of Puerto Rico and from 1898 to 1932 also called Porto Rico in English, is an unincorporated territory of the United States located in the northeast Caribbean Sea, approximately 1,000 miles (1,600 km) southeast of Miami, Florida.`,
  },
  {
    title: 'Providence',
    smallTitle: 'Providence <small>New Egland - Rhode Island - Usa',
    image1: '/assets/images/prov_1.jpg',
    image2: '/assets/images/prov_2.jpg',
    image3: '/assets/images/prov_3.jpg',
    imageBig: '/assets/images/prov_big.jpg',
    description: `Providence is the capital and most populous city of the state of Rhode Island and is one of the oldest cities in the United States. It was founded in 1636 by Roger Williams, a Reformed Baptist theologian and religious exile from the Massachusetts Bay Colony. He named the area in honor of "God's merciful Providence" which he believed was responsible for revealing such a haven for him and his followers.`,
  },
  {
    title: 'Fuerteventura',
    smallTitle: 'Canary Islands - Spain - Europe',
    image1: '/assets/images/fuerte_1.jpg',
    image2: '/assets/images/fuerte_2.jpg',
    image3: '/assets/images/fuerte_3.jpg',
    imageBig: '/assets/images/fuerte_big.jpg',
    description: `Fuerteventura is one of the Canary Islands, in the Atlantic Ocean and is part of the North Africa region, politically part of Spain. At 1,660 square kilometres (640 sq mi), it is the second largest of the Canary Islands, after Tenerife. As of 2019, Fuerteventura had 118,025 inhabitants. It was declared a biosphere reserve by UNESCO in May 2009.`,
  },
  {
    title: 'San Francisco',
    smallTitle: 'California - The city by the bay - Usa',
    image1: '/assets/images/sf_1.jpg',
    image2: '/assets/images/sf_2.jpg',
    image3: '/assets/images/sf_3.jpg',
    imageBig: '/assets/images/sf_big.jpg',
    description: `San Francisco, officially the City and County of San Francisco and colloquially known as SF, San Fran, Frisco, or The City, is the cultural, commercial, and financial center of Northern California. San Francisco is the 16th most populous city in the United States, and the fourth most populous in California, with 881,549 residents as of 2019. It covers an area of about 46.89 square miles (121.4 km2), mostly at the north end of the San Francisco Peninsula in the San Francisco Bay Area, making it the second most densely populated large U.S. city, and the fifth most densely populated U.S. county, behind only four of the five New York City boroughs. San Francisco is part of the 12th-largest metropolitan statistical area in the United States by population, with 4.7 million people, and the fourth-largest by economic output, with GDP of $592 billion in 2019. With San Jose, it forms the fifth most populous combined statistical area in the United States, the San Jose–San Francisco–Oakland, CA Combined Statistical Area.`,
  },
];
